### ISSUE TITLE
how i am able to print the seed words generated randomly?

### ISSUE THREAD

**Issue by AKGupta31** [tesseract-one/sr25519.swift#2]
I want to show seed words that have been generted randomly . How to do the same is showing the number of bytes when printing.

**Comment by ypopovych** [comment]
This library doesn't provide seed words functionality. It can generate a random seed, but you should use another library to convert it to words

**Comment by ypopovych** [comment]
We released a new library for Bip39 support. Check it, please, it will help you with seed words.

https://github.com/tesseract-one/Bip39.swift
